### ISSUE TITLE
Start and Stop Transactions are disabled. Can't use them.

### ISSUE THREAD

**Issue by tmb-01** [Lamerat/OCPP-Charge-Point-Simulator#2]

**Comment by Lamerat** [comment]
Hello,
before can use **START TRANSACTION**, charge point must be authorized from central system. First click button **AUTHORIZE**, and if central system accept this request, button START TRANSACTION will be enabled. Of course **STOP TRANSACTION** will be enable only if have active charging.
![Screen](https://github.com/Lamerat/OCPP-Charge-Point-Simulator/assets/83166598/32e168d1-9a5e-43a2-8588-d7713ad799bb)
