### ISSUE TITLE
why is this still charging?

### ISSUE THREAD

**Issue by tmb-01** [Lamerat/OCPP-Charge-Point-Simulator#3]
<img width="1440" alt="Screenshot 2024-01-11 at 22 02 19" src="https://github.com/Lamerat/OCPP-Charge-Point-Simulator/assets/55913644/b5f31649-8a0a-4e74-af2b-32c47225d40c">

after clicking stopTransaction I returned "Accepted" but it is still charging not stoping.

**Comment by Lamerat** [comment]
Can't tell you what is the reason. I make test with my OCPP central point server and everything is OK. I usually use the simulator for remote commands (that was the reason to create it), but with commands initiated from charge point again never haved problems.

![Screen](https://github.com/Lamerat/OCPP-Charge-Point-Simulator/assets/83166598/657996a4-caa7-427c-84ad-df755003a55e)
