### ISSUE TITLE
RemoteStopTransaction

### ISSUE THREAD

**Issue by BurakOgutken** [Lamerat/OCPP-Charge-Point-Simulator#5]
Hello, 

first of all, I really like the simulator; it's beautiful and works stably. However, I have a question: when I send a remote stop transaction, the stop transaction does not work. Could you help me figure out how to trigger this part? I would appreciate your assistance.

**Comment by Lamerat** [comment]
Hello,
I think this is function working fine, I'm used it many times. Maybe problem is you don't send correct transaction id. Check this part all is correct.
![sc](https://github.com/user-attachments/assets/5d542187-4b42-43c6-8c6b-58cb82b8ff1e)
